### PR TITLE
Use the latest code

### PR DESCRIPTION
**Pull request by aashishpanthi**

### CODE REVIEW

**Comment by aashishpanthi** [comment]
Use this code. They have changed the way we connect the metamask and other wallets. You can customize the UI and other things related to the wallet connection. Here is the official documentation: https://portal.thirdweb.com/react/v4/getting-started

**Comment by aashishpanthi** [comment]
Don't forget to create your own client id and use that, 
image

**Comment by aashishpanthi** [comment]
> Don't forget to create your own client id and use that, image

@ShubhamKPBoss Please read this instruction also.

**Comment by aashishpanthi** [comment]
The lastest commit solved the error @ShubhamKPBoss

**Comment by ShubhamKPBoss** [comment]
I have used the same git code. but still, I have the same issues and following  the official documentation: https://portal.thirdweb.com/react/v4/getting-started @aashishpanthi

**Comment by ShubhamKPBoss** [comment]
@aashishpanthi  hi, I have created a new client id but the same issues are coming after the Scann QR code

**Comment by aashishpanthi** [comment]
So, what I want you to do is:
1. Remove the project from your local directory
2. Clone this repository
3. Then install the dependencies using `npm i --legacy-peer-deps` command
4. Then inside of .env folder, enter your client id
5. With `npm start` command you'll see your application up and running

**Pull request merged**
